# Generated by Django 5.0.1 on 2024-01-22 07:32

import accounts.models.user
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.CreateModel(
            name='AddressVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal code')),
                ('file', models.FileField(upload_to=accounts.models.user.get_addr_doc_upload_path, verbose_name='File')),
                ('status', models.CharField(choices=[('waiting', 'Ожидается'), ('check', 'Проверка'), ('done', 'Пройдена'), ('failed', 'Отклонена')], default='waiting', verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('id_card', 'ID card'), ('residence_permit', 'Residence permit')], verbose_name='Document type')),
                ('document_issue_date', models.DateField(verbose_name='Document issue date')),
                ('file', models.FileField(upload_to=accounts.models.user.get_id_doc_upload_path, verbose_name='File')),
                ('status', models.CharField(choices=[('waiting', 'Ожидается'), ('check', 'Проверка'), ('done', 'Пройдена'), ('failed', 'Отклонена')], default='waiting', verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
