# Generated by Django 4.2.7 on 2024-01-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailconfirmationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='emailconfirmationtoken',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
