# Generated by Django 5.0.1 on 2024-01-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_docs_options_addressverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressverification',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидается'), ('check', 'Проверка'), ('done', 'Пройдена'), ('failed', 'Отклонена')], default='check', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='personalverification',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидается'), ('check', 'Проверка'), ('done', 'Пройдена'), ('failed', 'Отклонена')], default='check', verbose_name='Status'),
        ),
    ]
