# Generated by Django 5.0.1 on 2024-01-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
