# Generated by Django 5.0.1 on 2024-01-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_addressverification_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalverification",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                verbose_name="Gender",
            ),
            preserve_default=False,
        ),
    ]
