# Generated by Django 5.0.1 on 2024-01-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_personalverification_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressverification",
            name="status",
            field=models.CharField(
                choices=[
                    ("check", "Check"),
                    ("approved", "Approver"),
                    ("rejected", "Rejected"),
                ],
                default="check",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="personalverification",
            name="status",
            field=models.CharField(
                choices=[
                    ("check", "Check"),
                    ("approved", "Approver"),
                    ("rejected", "Rejected"),
                ],
                default="check",
                verbose_name="Status",
            ),
        ),
    ]
