# Generated by Django 5.0.1 on 2024-01-19 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_is_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verify_code', models.UUIDField(blank=True, null=True, verbose_name='Код для подтверждения почты')),
                ('email_verify_code_expires', models.DateTimeField(blank=True, null=True)),
                ('email_last_sending_code', models.DateTimeField(blank=True, null=True)),
                ('changing_password_code', models.UUIDField(blank=True, null=True, verbose_name='Код для смены пароля')),
                ('changing_password_code_expires', models.DateTimeField(blank=True, null=True, verbose_name='Время истечения кода')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коды подтверждения пользователя',
                'verbose_name_plural': 'Коды подтверждения пользователей',
            },
        ),
    ]
