# Generated by Django 5.0.1 on 2024-01-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tempdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdata',
            name='email_verify_code',
            field=models.CharField(blank=True, null=True, verbose_name='Код для подтверждения почты'),
        ),
        migrations.DeleteModel(
            name='EmailConfirmationToken',
        ),
    ]
