# Generated by Django 4.2.7 on 2024-01-24 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_addressverification_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.region",
                verbose_name="Region",
            ),
        ),
    ]
