# Generated by Django 4.2.7 on 2024-01-31 10:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31, verbose_name="Program name")),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duration (months)"
                    ),
                ),
                ("exp_profit", models.FloatField(verbose_name="Expected profit")),
                ("min_deposit", models.FloatField(verbose_name="Minimum deposit")),
                (
                    "accrual_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("after_end", "After end")],
                        verbose_name="Accrual type",
                    ),
                ),
                (
                    "withdrawal_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("after_end", "After end")],
                        verbose_name="Withdrawal type",
                    ),
                ),
                ("max_risk", models.FloatField(verbose_name="Maximum risk")),
                ("success_fee", models.FloatField(verbose_name="Success fee")),
                ("management_fee", models.FloatField(verbose_name="Management fee")),
                (
                    "withdrawal_term",
                    models.DurationField(verbose_name="Withdrawal term"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wallet",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("free", models.FloatField(default=0.0)),
                ("frozen", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="UserProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date(2024, 2, 5))),
                ("funds", models.FloatField(verbose_name="Underlying funds")),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="information.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("replenishment", "Replenishment"),
                            ("withdrawal", "Withdrawal"),
                            ("profit_bonus", "Profit Bonus"),
                            ("partner_bonus", "Partner Bonus"),
                            ("program_start", "Program Start"),
                            ("program_early_closure", "Program Early Closure"),
                            ("reinvesting", "Reinvesting"),
                            ("reinvesting_cancel", "Reinvesting Cancel"),
                            ("extra_fee", "Extra Fee"),
                            ("program_accrual", "Program Accrual"),
                        ],
                        verbose_name="Operation type",
                    ),
                ),
                ("amount", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="information.userprogram",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
