# Generated by Django 4.2.7 on 2024-02-05 11:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31, verbose_name="Program name")),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duration (months)"
                    ),
                ),
                ("exp_profit", models.FloatField(verbose_name="Expected profit")),
                ("min_deposit", models.FloatField(verbose_name="Minimum deposit")),
                (
                    "accrual_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("after_end", "After end")],
                        verbose_name="Accrual type",
                    ),
                ),
                (
                    "withdrawal_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("after_end", "After end")],
                        verbose_name="Withdrawal type",
                    ),
                ),
                ("max_risk", models.FloatField(verbose_name="Maximum risk")),
                ("success_fee", models.FloatField(verbose_name="Success fee")),
                ("management_fee", models.FloatField(verbose_name="Management fee")),
                (
                    "withdrawal_terms",
                    models.IntegerField(verbose_name="Withdrawal term (days)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=31, null=True)),
                ("start_date", models.DateField(default=datetime.date(2024, 2, 8))),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initial", "Ожидает запуска"),
                            ("running", "Запущена"),
                            ("finished", "Завершена"),
                        ],
                        default="initial",
                    ),
                ),
                (
                    "funds",
                    models.FloatField(default=0.0, verbose_name="Underlying funds"),
                ),
                ("force_closed", models.BooleanField(default=False)),
                ("last_replenishment", models.DateTimeField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="information.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wallet",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("free", models.FloatField(default=0.0)),
                ("frozen", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="UserProgramReplenishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initial", "Ожидает исполнения"),
                            ("done", "Исполнено"),
                            ("canceled", "Отменено"),
                        ],
                        default="initial",
                    ),
                ),
                ("apply_date", models.DateField(default=datetime.date(2024, 2, 8))),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replenishments",
                        to="information.userprogram",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprogram",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="information.wallet",
            ),
        ),
        migrations.CreateModel(
            name="ProgramResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.FloatField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="information.program",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("replenishment", "Replenishment"),
                            ("withdrawal", "Withdrawal"),
                            ("profit_bonus", "Profit Bonus"),
                            ("partner_bonus", "Partner Bonus"),
                            ("program_start", "Program Start"),
                            ("program_early_closure", "Program Early Closure"),
                            ("program_replenishment", "Program Replenishment"),
                            (
                                "program_replenishment_cancel",
                                "Program Replenishment Cancel",
                            ),
                            ("extra_fee", "Extra Fee"),
                            ("program_accrual", "Program Accrual"),
                        ],
                        verbose_name="Operation type",
                    ),
                ),
                ("amount_free", models.FloatField(default=0.0)),
                ("amount_frozen", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed", models.BooleanField(default=False)),
                ("done", models.BooleanField(default=False)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="information.userprogram",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="information.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FrozenItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("defrost_date", models.DateField(default=datetime.date(2024, 3, 6))),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frozen_items",
                        to="information.operation",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frozen_items",
                        to="information.wallet",
                    ),
                ),
            ],
        ),
    ]
