# Generated by Django 4.2.7 on 2024-02-01 09:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="program",
        ),
        migrations.RemoveField(
            model_name="operation",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprogram",
            name="user",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="frozen",
        ),
        migrations.AddField(
            model_name="operation",
            name="wallet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="information.wallet",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprogram",
            name="name",
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name="userprogram",
            name="wallet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="information.wallet",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="start_date",
            field=models.DateField(default=datetime.date(2024, 2, 6)),
        ),
        migrations.CreateModel(
            name="FrozenItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("until", models.DateField(default=datetime.date(2024, 3, 2))),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frozen_items",
                        to="information.operation",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frozen_items",
                        to="information.wallet",
                    ),
                ),
            ],
        ),
    ]
