# Generated by Django 4.2.7 on 2024-02-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="frozenitem",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
