# Generated by Django 4.2.7 on 2024-02-05 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0002_alter_userprogram_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogram",
            name="start_date",
            field=models.DateField(default=datetime.date(2024, 2, 8)),
        ),
    ]
