# Generated by Django 4.2.7 on 2024-02-05 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0002_frozenitem_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogram",
            name="user",
        ),
    ]
