# Generated by Django 4.2.7 on 2024-02-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0002_remove_operation_program_remove_operation_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="withdrawal_term",
        ),
        migrations.AddField(
            model_name="program",
            name="withdrawal_terms",
            field=models.IntegerField(
                default=30, verbose_name="Withdrawal term (days)"
            ),
            preserve_default=False,
        ),
    ]
