# Generated by Django 4.2.7 on 2024-02-01 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0003_remove_program_withdrawal_term_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogram",
            name="force_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="start_date",
            field=models.DateField(default=datetime.date(2024, 2, 5)),
        ),
    ]
