# Generated by Django 4.2.7 on 2024-02-09 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0003_alter_frozenitem_defrost_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="frozenitem",
            options={"ordering": ["-defrost_date"]},
        ),
        migrations.AddField(
            model_name="userprogram",
            name="deposit",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Underlying funds"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="accrual_type",
            field=models.CharField(
                choices=[("daily", "Daily")], verbose_name="Accrual type"
            ),
        ),
        migrations.AlterField(
            model_name="programresult",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="information.program",
            ),
        ),
        migrations.CreateModel(
            name="UserProgramAccrual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("success_fee", models.FloatField()),
                ("done", models.BooleanField(default=False)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accruals",
                        to="information.userprogram",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="operation",
            name="accrual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="information.userprogramaccrual",
            ),
        ),
    ]
