# Generated by Django 4.2.7 on 2024-02-06 08:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0003_remove_userprogram_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogram",
            name="last_replenishment",
        ),
        migrations.AddField(
            model_name="operation",
            name="amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="operation",
            name="replenishment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="information.userprogramreplenishment",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="user_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="information.userprogram",
            ),
        ),
        migrations.AlterField(
            model_name="frozenitem",
            name="defrost_date",
            field=models.DateField(default=datetime.date(2024, 3, 7)),
        ),
        migrations.AlterField(
            model_name="operation",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="information.program",
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="start_date",
            field=models.DateField(default=datetime.date(2024, 2, 9)),
        ),
        migrations.AlterField(
            model_name="userprogramreplenishment",
            name="apply_date",
            field=models.DateField(default=datetime.date(2024, 2, 9)),
        ),
    ]
