# Generated by Django 4.2.7 on 2024-02-12 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0004_alter_frozenitem_options_userprogram_deposit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frozenitem",
            name="done",
        ),
        migrations.AddField(
            model_name="frozenitem",
            name="force",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="frozenitem",
            name="frost_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="frozenitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("initial", "Ожидает разморозки"),
                    ("done", "Разморожено"),
                    ("canceled", "Отменено"),
                ],
                default="initial",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="frozen_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="information.frozenitem",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receives",
                to="information.wallet",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sends",
                to="information.wallet",
            ),
        ),
        migrations.AddField(
            model_name="userprogramaccrual",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprogramreplenishment",
            name="operation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="information.operation",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("replenishment", "Пополнение"),
                    ("withdrawal", "Вывод"),
                    ("transfer", "Перевод"),
                    ("partner_bonus", "Доход филиала"),
                    ("program_start", "Запуск программы"),
                    ("program_close", "Закрытие программы"),
                    ("program_replenishment", "Пополнение программы"),
                    ("program_replenishment_cancel", "Отмена пополнения программы"),
                    ("defrost", "Разморозка активов"),
                    ("extra_fee", "Списание комиссии Extra Fee"),
                    ("program_accrual", "Начисление по программе"),
                ],
                verbose_name="Operation type",
            ),
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=127, null=True)),
                (
                    "target",
                    models.CharField(
                        choices=[("wallet", "Wallet"), ("user_program", "User Program")]
                    ),
                ),
                (
                    "target_name",
                    models.CharField(blank=True, max_length=127, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("transfer_free", 'Перевод в раздел "Доступно"'),
                            ("transfer_frozen", 'Перевод в раздел "Заморожено"'),
                            ("transfer_between", "Перевод между счетами"),
                            ("withdrawal", "Вывод"),
                            ("replenishment", "Пополнение"),
                            ("profit_accrual", "Начисление прибыли"),
                            ("loss_chargeoff", "Фиксация убытка"),
                            ("loyalty_program", "Программа лояльности"),
                            ("system_message", "Системное сообщение"),
                        ]
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="information.operation",
                    ),
                ),
            ],
        ),
    ]
