# Generated by Django 4.2.7 on 2024-02-06 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0004_remove_userprogram_last_replenishment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frozenitem",
            name="operation",
        ),
    ]
