# Generated by Django 4.2.7 on 2024-02-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0004_userprogram_force_closed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogram",
            name="last_replenishment",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
