# Generated by Django 4.2.7 on 2024-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0005_remove_frozenitem_done_frozenitem_force_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frozenitem",
            name="force",
        ),
        migrations.AlterField(
            model_name="frozenitem",
            name="status",
            field=models.CharField(
                choices=[("initial", "Ожидает разморозки"), ("done", "Разморожено")],
                default="initial",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("replenishment", "Пополнение"),
                    ("withdrawal", "Вывод"),
                    ("transfer", "Перевод"),
                    ("partner_bonus", "Доход филиала"),
                    ("program_start", "Запуск программы"),
                    ("program_closure", "Закрытие программы"),
                    ("program_replenishment", "Пополнение программы"),
                    ("program_replenishment_cancel", "Отмена пополнения программы"),
                    ("defrost", "Разморозка активов"),
                    ("extra_fee", "Списание комиссии Extra Fee"),
                    ("program_accrual", "Начисление по программе"),
                ],
                verbose_name="Operation type",
            ),
        ),
    ]
