# Generated by Django 4.2.7 on 2024-02-01 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0005_userprogram_last_replenishment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="amount",
        ),
        migrations.AddField(
            model_name="operation",
            name="amount_free",
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="operation",
            name="amount_frozen",
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="operation",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operation",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operation",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="information.userprogram",
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="frozen",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("replenishment", "Replenishment"),
                    ("withdrawal", "Withdrawal"),
                    ("profit_bonus", "Profit Bonus"),
                    ("partner_bonus", "Partner Bonus"),
                    ("program_start", "Program Start"),
                    ("program_early_closure", "Program Early Closure"),
                    ("program_replenishment", "Program Replenishment"),
                    ("program_replenishment_cancel", "Program Replenishment Cancel"),
                    ("extra_fee", "Extra Fee"),
                    ("program_accrual", "Program Accrual"),
                ],
                verbose_name="Operation type",
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="funds",
            field=models.FloatField(default=0.0, verbose_name="Underlying funds"),
        ),
    ]
