# Generated by Django 4.2.7 on 2024-02-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0006_alter_wallethistory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallethistory",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
