# Generated by Django 4.2.7 on 2024-02-02 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0006_remove_operation_amount_operation_amount_free_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frozenitem",
            name="until",
            field=models.DateField(default=datetime.date(2024, 3, 3)),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="start_date",
            field=models.DateField(default=datetime.date(2024, 2, 6)),
        ),
    ]
