# Generated by Django 4.2.7 on 2024-02-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0007_alter_wallethistory_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallethistory",
            name="deposits",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Сумма базовых активов всех незакрытых программ",
            ),
        ),
    ]
