# Generated by Django 4.2.7 on 2024-02-13 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0008_alter_action_amount_alter_frozenitem_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"verbose_name": "Деталь", "verbose_name_plural": "Детали"},
        ),
        migrations.AlterModelOptions(
            name="frozenitem",
            options={
                "ordering": ["-defrost_date"],
                "verbose_name": "Замороженная сумма",
                "verbose_name_plural": "Замороженные средства",
            },
        ),
        migrations.AlterModelOptions(
            name="operation",
            options={"verbose_name": "Операция", "verbose_name_plural": "Операции"},
        ),
        migrations.AlterModelOptions(
            name="program",
            options={"verbose_name": "Программа", "verbose_name_plural": "Программы"},
        ),
        migrations.AlterModelOptions(
            name="programresult",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at"],
                "verbose_name": "Результат программы",
                "verbose_name_plural": "Результаты программ",
            },
        ),
        migrations.AlterModelOptions(
            name="userprogram",
            options={
                "verbose_name": "Программа пользователя",
                "verbose_name_plural": "Программы пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="userprogramaccrual",
            options={
                "verbose_name": "Начисление",
                "verbose_name_plural": "Начисления по программам",
            },
        ),
        migrations.AlterModelOptions(
            name="userprogramreplenishment",
            options={
                "verbose_name": "Пополнение",
                "verbose_name_plural": "Пополнения программ",
            },
        ),
        migrations.AlterModelOptions(
            name="wallet",
            options={"verbose_name": "Кошелёк", "verbose_name_plural": "Кошельки"},
        ),
        migrations.AlterField(
            model_name="action",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время"),
        ),
        migrations.AlterField(
            model_name="action",
            name="name",
            field=models.CharField(
                blank=True, max_length=127, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="information.operation",
                verbose_name="Операция",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="target",
            field=models.CharField(
                choices=[("wallet", "Wallet"), ("user_program", "User Program")],
                verbose_name="Объект",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="target_name",
            field=models.CharField(
                blank=True, max_length=127, null=True, verbose_name="Название объекта"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="type",
            field=models.CharField(
                choices=[
                    ("transfer_free", 'Перевод в раздел "Доступно"'),
                    ("transfer_frozen", 'Перевод в раздел "Заморожено"'),
                    ("transfer_between", "Перевод между счетами"),
                    ("withdrawal", "Вывод"),
                    ("replenishment", "Пополнение"),
                    ("profit_accrual", "Начисление прибыли"),
                    ("loss_chargeoff", "Фиксация убытка"),
                    ("loyalty_program", "Программа лояльности"),
                    ("system_message", "Системное сообщение"),
                ],
                verbose_name="Тип действия",
            ),
        ),
        migrations.AlterField(
            model_name="frozenitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма"
            ),
        ),
        migrations.AlterField(
            model_name="frozenitem",
            name="defrost_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Срок разморозки"
            ),
        ),
        migrations.AlterField(
            model_name="frozenitem",
            name="frost_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата заморозки"),
        ),
        migrations.AlterField(
            model_name="frozenitem",
            name="status",
            field=models.CharField(
                choices=[("initial", "Ожидает разморозки"), ("done", "Разморожено")],
                default="initial",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="frozenitem",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frozen_items",
                to="information.wallet",
                verbose_name="Кошелёк",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="accrual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="information.userprogramaccrual",
                verbose_name="Начисление",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Сумма"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="amount_free",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name='Из раздела "Свободно"',
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="amount_frozen",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name='Из раздела "Заморожено"',
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="confirmed",
            field=models.BooleanField(default=False, verbose_name="Подтверждена"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="done",
            field=models.BooleanField(default=False, verbose_name="Исполнена"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="frozen_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="information.frozenitem",
                verbose_name="Замороженная сумма",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="information.program",
                verbose_name="Программа",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receives",
                to="information.wallet",
                verbose_name="Получатель",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="replenishment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="information.userprogramreplenishment",
                verbose_name="Пополнение",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sends",
                to="information.wallet",
                verbose_name="Отправитель",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("replenishment", "Пополнение"),
                    ("withdrawal", "Вывод"),
                    ("transfer", "Перевод"),
                    ("partner_bonus", "Доход филиала"),
                    ("program_start", "Запуск программы"),
                    ("program_closure", "Закрытие программы"),
                    ("program_replenishment", "Пополнение программы"),
                    ("program_replenishment_cancel", "Отмена пополнения программы"),
                    ("defrost", "Разморозка активов"),
                    ("extra_fee", "Списание комиссии Extra Fee"),
                    ("program_accrual", "Начисление по программе"),
                ],
                verbose_name="Тип операции",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="user_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="information.userprogram",
                verbose_name="Программа пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="information.wallet",
                verbose_name="Кошелёк",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="accrual_type",
            field=models.CharField(
                choices=[("daily", "Daily")], verbose_name="Начисление прибыли"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="duration",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Продолжительность (мес)"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="exp_profit",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Ожидаемая доходность"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="management_fee",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Management Fee (в день)"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="max_risk",
            field=models.FloatField(verbose_name="Максимальный риск"),
        ),
        migrations.AlterField(
            model_name="program",
            name="min_deposit",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Минимальный депозит"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="name",
            field=models.CharField(max_length=31, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="program",
            name="success_fee",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Success Fee"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="withdrawal_terms",
            field=models.IntegerField(verbose_name="Срок вывода базового актива"),
        ),
        migrations.AlterField(
            model_name="program",
            name="withdrawal_type",
            field=models.CharField(
                choices=[("daily", "Daily"), ("after_end", "After end")],
                verbose_name="Вывод прибыли",
            ),
        ),
        migrations.AlterField(
            model_name="programresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время создания"
            ),
        ),
        migrations.AlterField(
            model_name="programresult",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="information.program",
                verbose_name="Программа",
            ),
        ),
        migrations.AlterField(
            model_name="programresult",
            name="result",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=6,
                verbose_name="Результат программы за прошедшие сутки (%) ",
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="deposit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Начальный депозит",
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="force_closed",
            field=models.BooleanField(
                default=False, verbose_name="Завершена принудительно"
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="funds",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Текущие средства",
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="name",
            field=models.CharField(
                blank=True, max_length=31, null=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="information.program",
                verbose_name="Программа",
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="status",
            field=models.CharField(
                choices=[
                    ("initial", "Ожидает запуска"),
                    ("running", "Запущена"),
                    ("finished", "Завершена"),
                ],
                default="initial",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="information.wallet",
                verbose_name="Кошелёк",
            ),
        ),
        migrations.AlterField(
            model_name="userprogramaccrual",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма начисления"
            ),
        ),
        migrations.AlterField(
            model_name="userprogramaccrual",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="userprogramaccrual",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accruals",
                to="information.userprogram",
                verbose_name="Программа",
            ),
        ),
        migrations.AlterField(
            model_name="userprogramaccrual",
            name="success_fee",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма Success Fee"
            ),
        ),
        migrations.AlterField(
            model_name="userprogramreplenishment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма"
            ),
        ),
        migrations.AlterField(
            model_name="userprogramreplenishment",
            name="apply_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Ожидаемая дата зачисления на счет программы",
            ),
        ),
        migrations.AlterField(
            model_name="userprogramreplenishment",
            name="operation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="information.operation",
                verbose_name="Операция",
            ),
        ),
        migrations.AlterField(
            model_name="userprogramreplenishment",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replenishments",
                to="information.userprogram",
                verbose_name="Программа",
            ),
        ),
        migrations.AlterField(
            model_name="userprogramreplenishment",
            name="status",
            field=models.CharField(
                choices=[
                    ("initial", "Ожидает исполнения"),
                    ("done", "Исполнено"),
                    ("canceled", "Отменено"),
                ],
                default="initial",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="free",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="frozen",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
