# Generated by Django 4.2.7 on 2024-02-13 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("information", "0009_alter_action_options_alter_frozenitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="accrual_type",
            field=models.CharField(
                choices=[("daily", "Ежедневно")], verbose_name="Начисление прибыли"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="exp_profit",
            field=models.FloatField(verbose_name="Ожидаемая доходность (%)"),
        ),
        migrations.AlterField(
            model_name="program",
            name="management_fee",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=6,
                verbose_name="Management Fee (%, в день)",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="max_risk",
            field=models.FloatField(verbose_name="Максимальный риск (%)"),
        ),
        migrations.AlterField(
            model_name="program",
            name="success_fee",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Success Fee (%)"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="withdrawal_terms",
            field=models.IntegerField(
                verbose_name="Срок вывода базового актива (дней)"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="withdrawal_type",
            field=models.CharField(
                choices=[
                    ("daily", "Ежедневно"),
                    ("after_finish", "По окончанию срока программы"),
                ],
                verbose_name="Вывод прибыли",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="free",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Доступно"
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="frozen",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Заморожено"
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="wallet",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
