# Generated by Django 4.2.7 on 2024-02-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0013_operation_early_closure_operation_partial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="accrual",
        ),
        migrations.AddField(
            model_name="operation",
            name="confirmation_code",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operation",
            name="confirmation_code_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
