# Generated by Django 4.2.7 on 2024-02-21 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0011_merge_20240214_1218"),
        (
            "information",
            "0014_remove_operation_accrual_operation_confirmation_code_and_more",
        ),
    ]

    operations = []
