# Generated by Django 4.2.7 on 2024-02-29 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0015_merge_20240221_1821"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogramaccrual",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accruals",
                to="information.userprogram",
                unique_for_date="created_at",
                verbose_name="Программа",
            ),
        ),
    ]
