# Generated by Django 4.2.7 on 2024-02-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0016_alter_userprogramaccrual_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogramaccrual",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accruals",
                to="information.userprogram",
                verbose_name="Программа",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprogramaccrual",
            constraint=models.UniqueConstraint(
                fields=("program", "created_at"), name="unique_program_created_at"
            ),
        ),
    ]
