# Generated by Django 4.2.7 on 2024-03-04 13:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0020_userprogramaccrual_percent_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProgramHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "funds",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=10,
                        verbose_name="Торговые средства",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=10,
                        verbose_name="Суммарный доход",
                    ),
                ),
                (
                    "user_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_program_history",
                        to="information.userprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "История программы пользователя",
                "verbose_name_plural": "Истории программ пользователя",
                "unique_together": {("user_program", "created_at")},
            },
        ),
    ]
