# Generated by Django 4.2.7 on 2024-03-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0021_userprogramhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogramaccrual",
            name="management_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Сумма Management Fee",
            ),
            preserve_default=False,
        ),
    ]
