# Generated by Django 4.2.7 on 2024-03-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0023_userprogramreplenishment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogramhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("initial", "Ожидает запуска"),
                    ("running", "Запущена"),
                    ("finished", "Завершена"),
                ],
                default="initial",
                verbose_name="Статус",
            ),
        ),
    ]
