# Generated by Django 4.2.7 on 2024-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0024_userprogramhistory_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holidays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Не заполняйте для праздника длящегося один день",
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Праздник",
                "verbose_name_plural": "Праздники",
            },
        ),
    ]
