# Generated by Django 4.2.7 on 2024-03-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0025_holidays"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
