# Generated by Django 4.2.7 on 2024-03-27 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0026_operation_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
