# Generated by Django 4.2.7 on 2024-04-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0029_alter_userprogramaccrual_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogramreplenishment",
            name="operation",
        ),
        migrations.AddField(
            model_name="userprogramreplenishment",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="operation",
            name="replenishment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation",
                to="information.userprogramreplenishment",
                verbose_name="Пополнение",
            ),
        ),
        migrations.AlterField(
            model_name="userprogramreplenishment",
            name="apply_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата зачисления на счет программы"
            ),
        ),
        migrations.CreateModel(
            name="OperationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("transfer_free", 'Перевод в раздел "Доступно"'),
                            ("transfer_frozen", 'Перевод в раздел "Заморожено"'),
                            ("transfer_between", "Перевод между счетами"),
                            ("withdrawal", "Вывод"),
                            ("replenishment", "Пополнение"),
                            ("profit_accrual", "Начисление прибыли"),
                            ("loss_chargeoff", "Фиксация убытка"),
                            ("loyalty_program", "Программа лояльности"),
                            ("system_message", "Системное сообщение"),
                        ],
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=127, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        blank=True,
                        max_length=127,
                        null=True,
                        verbose_name="Название объекта",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations_history",
                        to="information.wallet",
                        verbose_name="Кошелёк",
                    ),
                ),
            ],
            options={
                "verbose_name": "История операций",
                "verbose_name_plural": "Истории операций",
            },
        ),
    ]
