# Generated by Django 4.2.7 on 2024-04-11 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0031_alter_userprogramaccrual_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="address",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="T[A-Za-z1-9]{33}")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="operationhistory",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Сумма",
            ),
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сумма без учета комиссии",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сумма c учётом комиссии",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="T[A-Za-z1-9]{33}"
                            )
                        ],
                        verbose_name="Адрес TRC-20",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидание"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                        ],
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "reject_message",
                    models.TextField(blank=True, verbose_name="Причина отказа"),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="information.wallet",
                        verbose_name="Кошелёк",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки на вывод средств",
            },
        ),
    ]
