# Generated by Django 4.2.7 on 2024-02-08 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frozenitem",
            name="defrost_date",
            field=models.DateField(default=datetime.date(2024, 3, 9)),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="start_date",
            field=models.DateField(default=datetime.date(2024, 2, 13)),
        ),
        migrations.AlterField(
            model_name="userprogramreplenishment",
            name="apply_date",
            field=models.DateField(default=datetime.date(2024, 2, 13)),
        ),
    ]
