# Generated by Django 4.2.7 on 2024-02-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_alter_frozenitem_defrost_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frozenitem",
            name="defrost_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprogramreplenishment",
            name="apply_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
