# Generated by Django 4.2.7 on 2024-02-13 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_wallethistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallethistory",
            options={
                "verbose_name": "История кошелька",
                "verbose_name_plural": "Истории кошельков",
            },
        ),
    ]
