# Generated by Django 4.2.7 on 2024-02-13 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "finance",
            "0006_remove_frozenitem_force_alter_frozenitem_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogramaccrual",
            name="done",
        ),
    ]
