# Generated by Django 4.2.7 on 2024-02-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_remove_userprogramaccrual_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="amount",
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.AlterField(
            model_name="frozenitem",
            name="amount",
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.AlterField(
            model_name="operation",
            name="amount",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="operation",
            name="amount_free",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="operation",
            name="amount_frozen",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="program",
            name="exp_profit",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Expected profit"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="management_fee",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Management fee"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="min_deposit",
            field=models.DecimalField(
                decimal_places=8, max_digits=16, verbose_name="Minimum deposit"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="success_fee",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Success fee"
            ),
        ),
        migrations.AlterField(
            model_name="programresult",
            name="result",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="deposit",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=16,
                null=True,
                verbose_name="Underlying funds",
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="funds",
            field=models.DecimalField(
                decimal_places=8,
                default=0.0,
                max_digits=16,
                verbose_name="Underlying funds",
            ),
        ),
        migrations.AlterField(
            model_name="userprogramaccrual",
            name="amount",
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.AlterField(
            model_name="userprogramaccrual",
            name="success_fee",
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.AlterField(
            model_name="userprogramreplenishment",
            name="amount",
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="free",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="frozen",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
    ]
