# Generated by Django 4.2.7 on 2024-02-14 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_alter_wallethistory_deposits"),
        (
            "finance",
            "0010_alter_program_accrual_type_alter_program_exp_profit_and_more",
        ),
    ]

    operations = []
