# Generated by Django 4.2.7 on 2024-02-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "finance",
            "0010_alter_program_accrual_type_alter_program_exp_profit_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Сумма",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="amount_free",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name='Из раздела "Свободно"',
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="amount_frozen",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name='Из раздела "Заморожено"',
            ),
        ),
    ]
