# Generated by Django 4.2.7 on 2024-02-15 12:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "finance",
            "0011_alter_operation_amount_alter_operation_amount_free_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogram",
            name="force_closed",
        ),
        migrations.AddField(
            model_name="userprogram",
            name="close_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Фактическая дата завершения"
            ),
        ),
        migrations.AddField(
            model_name="userprogram",
            name="profit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                max_digits=10,
                verbose_name="Суммарный доход",
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                max_digits=10,
                verbose_name="Базовый депозит",
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Планируемая дата завершения"
            ),
        ),
        migrations.AlterField(
            model_name="userprogram",
            name="funds",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                max_digits=10,
                verbose_name="Текущие торговые средства",
            ),
        ),
    ]
