# Generated by Django 4.2.7 on 2024-02-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0012_remove_userprogram_force_closed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="early_closure",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operation",
            name="partial",
            field=models.BooleanField(default=False),
        ),
    ]
