# Generated by Django 4.2.7 on 2024-02-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0017_alter_userprogramaccrual_program_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userprogramaccrual",
            name="unique_program_created_at",
        ),
        migrations.AlterField(
            model_name="programresult",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата и время создания"
            ),
        ),
        migrations.AddConstraint(
            model_name="programresult",
            constraint=models.UniqueConstraint(
                fields=("program", "created_at"),
                name="unique_program_result_created_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprogramaccrual",
            constraint=models.UniqueConstraint(
                fields=("program", "created_at"),
                name="unique_program_accrual_created_at",
            ),
        ),
    ]
