# Generated by Django 4.2.7 on 2024-02-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "finance",
            "0018_remove_userprogramaccrual_unique_program_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="programresult",
            name="created_at",
            field=models.DateField(verbose_name="Дата и время создания"),
        ),
    ]
