# Generated by Django 4.2.7 on 2024-03-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0019_alter_programresult_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogramaccrual",
            name="percent_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=6,
                verbose_name="Сумма начисления в процентах от депозита",
            ),
            preserve_default=False,
        ),
    ]
