# Generated by Django 4.2.7 on 2024-03-05 10:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0022_userprogramaccrual_management_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogramreplenishment",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания вывода",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprogramreplenishment",
            name="operation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_repl",
                to="finance.operation",
                verbose_name="Операция",
            ),
        ),
    ]
