# Generated by Django 4.2.7 on 2024-04-03 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0027_operation_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programresult",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at"],
                "verbose_name": "Результат программы",
                "verbose_name_plural": "Результаты программ",
            },
        ),
    ]
