# Generated by Django 4.2.7 on 2024-04-03 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0028_alter_programresult_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprogramaccrual",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Начисление",
                "verbose_name_plural": "Начисления по программам",
            },
        ),
    ]
