# Generated by Django 4.2.7 on 2024-04-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0030_remove_userprogramreplenishment_operation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogramaccrual",
            name="created_at",
            field=models.DateField(verbose_name="Дата"),
        ),
    ]
