# Generated by Django 4.2.7 on 2024-04-11 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "finance",
            "0032_operation_address_alter_operationhistory_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationhistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "История операций",
                "verbose_name_plural": "Истории операций",
            },
        ),
    ]
