# Generated by Django 4.2.7 on 2024-04-15 00:15

import core.localized.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0033_alter_operationhistory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationhistory",
            name="description",
            field=core.localized.fields.LocalizedCharField(
                blank=True,
                max_length=127,
                null=True,
                required=[],
                verbose_name="Описание",
            ),
        ),
    ]
