# Generated by Django 4.2.7 on 2024-04-19 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0034_alter_operationhistory_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogram",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="operationhistory",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время"
            ),
        ),
        migrations.AlterField(
            model_name="userprogramreplenishment",
            name="created_at",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата создания вывода"
            ),
        ),
    ]
