# Generated by Django 4.2.7 on 2024-04-19 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0035_userprogram_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
