# Generated by Django 4.2.7 on 2024-04-24 10:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0036_withdrawalrequest_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("wallet", "Сумма в кошельках"),
                            ("st_1", "Сумма в программах ST-1"),
                            ("st_2", "Сумма в программах ST-2"),
                            ("st_3", "Сумма в программах ST-3"),
                            ("to_withdraw", "Поставлено на вывод (кошелёк)"),
                            ("to_start", "Ожидает запуска"),
                            ("to_replenish", "Ожидает пополнения"),
                            ("branch_ru", "Доход филиала Россия"),
                            ("branch_cn", "Доход филиала Китай"),
                            ("branch_us", "Доход филиала США"),
                            ("net_profit", "Начисленная прибыль (чистая)"),
                            ("gross_profit", "Начисленная прибыль (базовая)"),
                            ("success_fee", "Удержано Success Fee"),
                            (
                                "success_fee_net",
                                "Удержано Success Fee после вычета дохода Филиала",
                            ),
                            ("extra_fee", "Удержано Extra Fee"),
                            ("management_fee", "Удержано Management Fee"),
                            ("total_fund_balance", "Итого Баланс Фонда"),
                            ("users_total", "Кол-во зарегистрированных пользователей"),
                            ("users_active", "Кол-во активных пользователей"),
                        ],
                        unique=True,
                        verbose_name="Показатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Показатель",
                "verbose_name_plural": "Баланс фонда (статистика)",
            },
        ),
        migrations.AddField(
            model_name="userprogramhistory",
            name="deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                max_digits=10,
                verbose_name="Депозит",
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="done_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Проведена транзакция"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="address",
            field=models.CharField(
                validators=[
                    django.core.validators.RegexValidator(regex="T[A-Za-z1-9]{33}")
                ],
                verbose_name="Адрес криптокошелька",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Перевести инвестору"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="done",
            field=models.BooleanField(
                default=False, verbose_name="Отметка о выполнении"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="original_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Списать с кошелька"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание"),
                    ("approved", "Одобрена"),
                    ("rejected", "Отклонена"),
                ],
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdrawal_requests",
                to="finance.wallet",
                verbose_name="ID",
            ),
        ),
    ]
