# Generated by Django 4.2.7 on 2024-04-26 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0038_alter_stats_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="confirmation_code",
        ),
        migrations.RemoveField(
            model_name="operation",
            name="confirmation_code_expires_at",
        ),
        migrations.RemoveField(
            model_name="operation",
            name="confirmed",
        ),
        migrations.CreateModel(
            name="OperationConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        choices=[("email", "Email"), ("telegram", "Telegram")]
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmations",
                        to="finance.operation",
                    ),
                ),
            ],
        ),
    ]
