# Generated by Django 4.2.7 on 2024-05-02 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0039_remove_operation_confirmation_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationSummary",
            fields=[],
            options={
                "verbose_name": "Транзакции",
                "verbose_name_plural": "Транзакции",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.operation",),
        ),
        migrations.AlterModelOptions(
            name="programresult",
            options={
                "verbose_name": "настройки программ",
                "verbose_name_plural": "Настройки программ",
            },
        ),
        migrations.RemoveConstraint(
            model_name="programresult",
            name="unique_program_result_created_at",
        ),
        migrations.RemoveField(
            model_name="programresult",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="programresult",
            name="program",
        ),
        migrations.AddField(
            model_name="programresult",
            name="_singleton",
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="programresult",
            name="apply_time",
            field=models.TimeField(
                default=django.utils.timezone.now,
                verbose_name="Время ежедневных начислений",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="programresult",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="programresult",
            name="until",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Актуально до"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programresult",
            name="result",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Дневная доходность (%) "
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="done",
            field=models.BooleanField(default=False, verbose_name="Выполнено"),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="done_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата выполнения"
            ),
        ),
    ]
