# Generated by Django 4.2.7 on 2024-05-02 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0039_remove_operation_confirmation_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время"
            ),
        ),
    ]
