# Generated by Django 4.2.7 on 2024-05-02 12:14

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0040_operationsummary_alter_programresult_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programresult",
            options={
                "verbose_name": "настройки начислений",
                "verbose_name_plural": "Настройки начислений",
            },
        ),
        migrations.AddField(
            model_name="operation",
            name="amount_net",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Сумма с учётом комиссии",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="commission",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Комиссия",
            ),
        ),
        migrations.CreateModel(
            name="WalletSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "defrost_days",
                    models.PositiveIntegerField(
                        default=30,
                        verbose_name="Время разморозки Базовых Активов (дней)",
                    ),
                ),
                (
                    "commission_on_replenish",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.5"),
                        max_digits=6,
                        verbose_name="Комиссия за пополнение, %",
                    ),
                ),
                (
                    "commission_on_withdraw",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.5"),
                        max_digits=6,
                        verbose_name="Комиссия за вывод, %",
                    ),
                ),
                (
                    "commission_success_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30.0"),
                        max_digits=6,
                        verbose_name="Комиссия Success fee, %",
                    ),
                ),
                (
                    "commission_management_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.004"),
                        max_digits=6,
                        verbose_name="Комиссия Management fee, %",
                    ),
                ),
                (
                    "commission_extra_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.0"),
                        max_digits=6,
                        verbose_name="Комиссия Extra fee, %",
                    ),
                ),
                (
                    "commission_on_transfer",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.5"),
                        max_digits=6,
                        verbose_name="Комиссия за внутренний перевод",
                    ),
                ),
                (
                    "wallet",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="finance.wallet",
                        verbose_name="Настройки",
                    ),
                ),
            ],
        ),
    ]
