# Generated by Django 4.2.7 on 2024-05-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0041_alter_programresult_options_operation_amount_net_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletsettings",
            name="commission_extra_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Комиссия Extra fee, %",
            ),
        ),
        migrations.AlterField(
            model_name="walletsettings",
            name="commission_management_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Комиссия Management fee, %",
            ),
        ),
        migrations.AlterField(
            model_name="walletsettings",
            name="commission_on_replenish",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Комиссия за пополнение, %",
            ),
        ),
        migrations.AlterField(
            model_name="walletsettings",
            name="commission_on_transfer",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Комиссия за внутренний перевод, %",
            ),
        ),
        migrations.AlterField(
            model_name="walletsettings",
            name="commission_on_withdraw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Комиссия за вывод, %",
            ),
        ),
        migrations.AlterField(
            model_name="walletsettings",
            name="commission_success_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Комиссия Success fee, %",
            ),
        ),
        migrations.AlterField(
            model_name="walletsettings",
            name="defrost_days",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Время разморозки Базовых Активов (дней)",
            ),
        ),
    ]
