# Generated by Django 4.2.7 on 2024-05-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0042_alter_walletsettings_commission_extra_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletsettings",
            name="commission_management_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=6,
                null=True,
                verbose_name="Комиссия Management fee, %",
            ),
        ),
    ]
