# Generated by Django 4.2.7 on 2024-05-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0043_alter_walletsettings_commission_management_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="walletsettings",
            name="commission_extra_fee",
        ),
        migrations.RemoveField(
            model_name="walletsettings",
            name="commission_management_fee",
        ),
        migrations.RemoveField(
            model_name="walletsettings",
            name="commission_success_fee",
        ),
        migrations.AddField(
            model_name="walletsettings",
            name="extra_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Extra fee, %",
            ),
        ),
        migrations.AddField(
            model_name="walletsettings",
            name="management_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=6,
                null=True,
                verbose_name="Management fee, %",
            ),
        ),
        migrations.AddField(
            model_name="walletsettings",
            name="success_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Success fee, %",
            ),
        ),
    ]
