# Generated by Django 4.2.7 on 2024-05-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0044_remove_walletsettings_commission_extra_fee_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Операция",
                "verbose_name_plural": "Операции",
            },
        ),
        migrations.AlterModelOptions(
            name="walletsettings",
            options={
                "verbose_name": "настройки",
                "verbose_name_plural": "Общие настройки",
            },
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdrawal_requests",
                to="finance.operation",
                verbose_name="Заявки на вывод",
            ),
        ),
    ]
