# Generated by Django 4.2.7 on 2024-05-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0040_alter_operation_created_at"),
        (
            "finance",
            "0045_alter_operation_options_alter_walletsettings_options_and_more",
        ),
    ]

    operations = []
