# Generated by Django 4.2.7 on 2024-05-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0046_merge_20240502_1818"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "транзакцию",
                "verbose_name_plural": "Транзакции",
            },
        ),
    ]
