# Generated by Django 4.2.7 on 2024-05-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0048_remove_program_management_fee_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={
                "ordering": ["name"],
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы",
            },
        ),
    ]
