# Generated by Django 4.2.7 on 2024-05-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0050_alter_stats_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.CharField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=63, null=True)),
            ],
        ),
    ]
