# Generated by Django 4.2.7 on 2024-05-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0052_alter_stats_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="masterwallet",
            options={
                "verbose_name": "Мастер-кошелёк",
                "verbose_name_plural": "Мастер-кошелёк",
            },
        ),
    ]
