# Generated by Django 4.2.7 on 2024-05-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0053_alter_masterwallet_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="withdrawal_terms",
        ),
    ]
