# Generated by Django 4.2.7 on 2024-05-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0054_remove_program_withdrawal_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="commission",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Удержать комиссию",
            ),
            preserve_default=False,
        ),
    ]
