# Generated by Django 4.2.7 on 2024-05-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0055_withdrawalrequest_commission"),
    ]

    operations = [
        migrations.AddField(
            model_name="frozenitem",
            name="frost_datetime",
            field=models.DateField(blank=True, null=True),
        ),
    ]
