# Generated by Django 4.2.7 on 2024-05-14 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0056_frozenitem_frost_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="created_at",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Поставлено на вывод"
            ),
        ),
    ]
