# Generated by Django 4.2.7 on 2024-05-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0057_alter_withdrawalrequest_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationhistory",
            name="operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="finance.operation",
            ),
        ),
    ]
