# Generated by Django 4.2.7 on 2024-05-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0058_operationhistory_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("replenishment", "Пополнение"),
                    ("withdrawal", "Снятие"),
                    ("transfer", "Перевод"),
                    ("partner_bonus", "Доход филиала"),
                    ("program_start", "Запуск программы"),
                    ("program_closure", "Закрытие программы"),
                    ("program_replenishment", "Пополнение программы"),
                    ("program_replenishment_cancel", "Отмена пополнения программы"),
                    ("defrost", "Разморозка активов"),
                    ("extra_fee", "Списание комиссии Extra Fee"),
                    ("program_accrual", "Начисление по программе"),
                ],
                verbose_name="Тип операции",
            ),
        ),
    ]
