# Generated by Django 4.2.7 on 2024-05-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0059_alter_operation_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationhistory",
            name="operation",
        ),
        migrations.AddField(
            model_name="operationhistory",
            name="operation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("replenishment", "Пополнение"),
                    ("withdrawal", "Снятие"),
                    ("transfer", "Перевод"),
                    ("partner_bonus", "Доход филиала"),
                    ("program_start", "Запуск программы"),
                    ("program_closure", "Закрытие программы"),
                    ("program_replenishment", "Пополнение программы"),
                    ("program_replenishment_cancel", "Отмена пополнения программы"),
                    ("defrost", "Разморозка активов"),
                    ("extra_fee", "Списание комиссии Extra Fee"),
                    ("program_accrual", "Начисление по программе"),
                ],
                null=True,
            ),
        ),
    ]
