# Generated by Django 4.2.7 on 2024-05-22 16:20

import core.localized.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0060_remove_operationhistory_operation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            (
                                "withdrawal_request_created",
                                "Withdrawal Request Created",
                            ),
                            (
                                "withdrawal_request_approved",
                                "Withdrawal Request Approved",
                            ),
                            (
                                "withdrawal_request_rejected",
                                "Withdrawal Request Rejected",
                            ),
                            ("transfer_sent", "Transfer Sent"),
                            ("transfer_received", "Transfer Received"),
                            ("transfer_to_program", "Transfer To Program"),
                            ("program_start", "Program Start"),
                            ("program_started", "Program Started"),
                            ("program_replenishment", "Program Replenishment"),
                            ("program_replenished", "Program Replenished"),
                            (
                                "program_replenishment_cancel",
                                "Program Replenishment Cancel",
                            ),
                            (
                                "program_replenishment_cancel_partial",
                                "Program Replenishment Cancel Partial",
                            ),
                            ("program_closed", "Program Closure"),
                            ("program_closed_early", "Program Closure Early"),
                            ("program_closure_partial", "Program Closure Partial"),
                            ("program_accrual_profit", "Program Accrual Profit"),
                            ("program_accrual_loss", "Program Accrual Loss"),
                            ("branch_income", "Branch Income"),
                            ("deposit_transfer", "Deposit Transfer"),
                            ("frozen_available", "Frozen Available"),
                            ("force_defrost", "Force Defrost"),
                            ("extra_fee", "Extra Fee"),
                        ],
                        max_length=40,
                        unique=True,
                        verbose_name="Тип сообщения",
                    ),
                ),
                (
                    "text",
                    core.localized.fields.LocalizedTextField(
                        required=["ru"], verbose_name="Основной текст"
                    ),
                ),
            ],
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "Уведомления в истории операций",
            },
        ),
    ]
