# Generated by Django 4.2.7 on 2024-05-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0063_alter_operationhistory_message_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("replenishment", "Пополнение"),
                    ("withdrawal", "Снятие"),
                    ("transfer", "Перевод"),
                    ("branch_income", "Доход филиала"),
                    ("program_start", "Запуск программы"),
                    ("program_closure", "Закрытие программы"),
                    ("program_replenishment", "Пополнение программы"),
                    ("program_replenishment_cancel", "Отмена пополнения программы"),
                    ("defrost", "Разморозка активов"),
                    ("extra_fee", "Списание комиссии Extra Fee"),
                    ("program_accrual", "Начисление по программе"),
                ],
                verbose_name="Тип операции",
            ),
        ),
        migrations.AlterField(
            model_name="operationhistory",
            name="operation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("replenishment", "Пополнение"),
                    ("withdrawal", "Снятие"),
                    ("transfer", "Перевод"),
                    ("branch_income", "Доход филиала"),
                    ("program_start", "Запуск программы"),
                    ("program_closure", "Закрытие программы"),
                    ("program_replenishment", "Пополнение программы"),
                    ("program_replenishment_cancel", "Отмена пополнения программы"),
                    ("defrost", "Разморозка активов"),
                    ("extra_fee", "Списание комиссии Extra Fee"),
                    ("program_accrual", "Начисление по программе"),
                ],
                null=True,
            ),
        ),
    ]
