# Generated by Django 4.2.7 on 2024-05-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0064_alter_operation_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogram",
            name="funds",
        ),
        migrations.RemoveField(
            model_name="userprogram",
            name="profit",
        ),
    ]
