# Generated by Django 4.2.7 on 2024-05-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0065_remove_userprogram_funds_remove_userprogram_profit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Action",
        ),
    ]
