# Generated by Django 4.2.7 on 2024-05-23 14:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0066_delete_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="min_replenishment",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100.00"),
                max_digits=10,
                verbose_name="Минимальная сумма пополнения",
            ),
        ),
    ]
