# Generated by Django 4.2.7 on 2024-05-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0067_program_min_replenishment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stats",
            name="name",
            field=models.CharField(
                choices=[
                    ("wallet", "Сумма в кошельках"),
                    ("st_1", "Сумма в программах ST-1"),
                    ("st_2", "Сумма в программах ST-2"),
                    ("st_3", "Сумма в программах ST-3"),
                    ("to_withdraw", "Поставлено на вывод (ожидает рассмотрения)"),
                    ("to_start", "Ожидает запуска"),
                    ("to_replenish", "Ожидает пополнения"),
                    ("total_fund_balance", "ИТОГО БАЛАНС ФОНДА"),
                    ("branch_ru", "Доход филиала Россия"),
                    ("branch_cn", "Доход филиала Китай"),
                    ("branch_us", "Доход филиала США"),
                    ("net_profit", "Начисленная прибыль (чистая)"),
                    ("gross_profit", "Начисленная прибыль (базовая)"),
                    ("success_fee", "Удержано Success Fee"),
                    (
                        "success_fee_net",
                        "Удержано Success Fee после вычета дохода Филиала",
                    ),
                    ("extra_fee", "Удержано Extra Fee"),
                    ("management_fee", "Удержано Management Fee"),
                    ("users_total", "Кол-во зарегистрированных пользователей"),
                    ("users_active", "Кол-во активных пользователей"),
                ],
                unique=True,
                verbose_name="Показатель",
            ),
        ),
    ]
