# Generated by Django 4.2.7 on 2024-05-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0068_alter_stats_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationhistory",
            name="message_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("withdrawal_request_created", "Заявка на вывод создана"),
                    ("withdrawal_request_approved", "Заявка на вывод подтверждена"),
                    ("withdrawal_request_rejected", "Заявка на вывод отклонена"),
                    ("transfer_sent", "Внутренний перевод отправлен"),
                    ("transfer_received", "Внутренний перевод получен"),
                    ("transfer_to_program", "Перевод в программу"),
                    ("program_start", "Запуск программы"),
                    ("program_replenished", "Программа пополнена"),
                    ("program_replenishment_cancel", "Отмена пополнения программы"),
                    (
                        "program_replenishment_cancel_partial",
                        "Частичная отмена пополнения программы",
                    ),
                    ("program_closed", "Закрытие программы"),
                    ("program_closed_early", "Досрочное закрытие программы"),
                    ("program_closure_partial", "Частичное закрытие программы"),
                    ("program_accrual_profit", "Прибыль по программе"),
                    ("program_accrual_loss", "Отрицательная прибыль по программе"),
                    ("branch_income", "Доход филиала"),
                    ("deposit_transfer", "Вывод депозита из программы"),
                    ("frozen_available", "Разморозка средств"),
                    ("force_defrost", "Досрочная разморозка средств"),
                    ("extra_fee", "Списание Extra Fee"),
                    ("replenishment", "Пополнение кошелька"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="operationmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("withdrawal_request_created", "Заявка на вывод создана"),
                    ("withdrawal_request_approved", "Заявка на вывод подтверждена"),
                    ("withdrawal_request_rejected", "Заявка на вывод отклонена"),
                    ("transfer_sent", "Внутренний перевод отправлен"),
                    ("transfer_received", "Внутренний перевод получен"),
                    ("transfer_to_program", "Перевод в программу"),
                    ("program_start", "Запуск программы"),
                    ("program_replenished", "Программа пополнена"),
                    ("program_replenishment_cancel", "Отмена пополнения программы"),
                    (
                        "program_replenishment_cancel_partial",
                        "Частичная отмена пополнения программы",
                    ),
                    ("program_closed", "Закрытие программы"),
                    ("program_closed_early", "Досрочное закрытие программы"),
                    ("program_closure_partial", "Частичное закрытие программы"),
                    ("program_accrual_profit", "Прибыль по программе"),
                    ("program_accrual_loss", "Отрицательная прибыль по программе"),
                    ("branch_income", "Доход филиала"),
                    ("deposit_transfer", "Вывод депозита из программы"),
                    ("frozen_available", "Разморозка средств"),
                    ("force_defrost", "Досрочная разморозка средств"),
                    ("extra_fee", "Списание Extra Fee"),
                    ("replenishment", "Пополнение кошелька"),
                ],
                max_length=40,
                unique=True,
                verbose_name="Тип сообщения",
            ),
        ),
    ]
