# Generated by Django 4.2.7 on 2024-06-11 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0069_alter_operationhistory_message_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("replenishment", "Комиссия с пополнений"),
                            ("withdrawal", "Комиссия со снятий"),
                            ("transfer", "Комиссия с внутренних переводов"),
                            ("success_fee", "Success fee"),
                            ("management_fee", "Management fee"),
                            ("extra_fee", "Extra fee"),
                        ]
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
