# Generated by Django 4.2.7 on 2024-06-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0071_alter_operation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationhistory",
            name="is_commission",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Commission",
        ),
    ]
