# Generated by Django 4.2.7 on 2024-06-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0072_operationhistory_is_commission_delete_commission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[
                    ("replenishment", "Пополнение"),
                    ("withdrawal", "Снятие"),
                    ("transfer", "Перевод"),
                    ("branch_income", "Доход филиала"),
                    ("program_start", "Запуск программы"),
                    ("program_closure", "Закрытие программы"),
                    ("program_replenishment", "Пополнение программы"),
                    ("program_replenishment_cancel", "Отмена пополнения программы"),
                    ("defrost", "Разморозка активов"),
                    ("extra_fee_writeoff", "Списание комиссии Extra Fee"),
                    ("program_accrual", "Начисление по программе"),
                    ("replenishment_fee", "Комиссия за пополнения"),
                    ("withdrawal_fee", "Комиссия за вывод средств"),
                    ("transfer_fee", "Комиссия за внутренние переводы"),
                    ("success_fee", "Success fee"),
                    ("management_fee", "Management fee"),
                    ("extra_fee", "Extra fee"),
                ],
                verbose_name="Тип операции",
            ),
        ),
        migrations.AlterField(
            model_name="operationhistory",
            name="operation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("replenishment", "Пополнение"),
                    ("withdrawal", "Снятие"),
                    ("transfer", "Перевод"),
                    ("branch_income", "Доход филиала"),
                    ("program_start", "Запуск программы"),
                    ("program_closure", "Закрытие программы"),
                    ("program_replenishment", "Пополнение программы"),
                    ("program_replenishment_cancel", "Отмена пополнения программы"),
                    ("defrost", "Разморозка активов"),
                    ("extra_fee_writeoff", "Списание комиссии Extra Fee"),
                    ("program_accrual", "Начисление по программе"),
                    ("replenishment_fee", "Комиссия за пополнения"),
                    ("withdrawal_fee", "Комиссия за вывод средств"),
                    ("transfer_fee", "Комиссия за внутренние переводы"),
                    ("success_fee", "Success fee"),
                    ("management_fee", "Management fee"),
                    ("extra_fee", "Extra fee"),
                ],
                null=True,
            ),
        ),
    ]
