# Generated by Django 4.2.7 on 2024-06-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0073_alter_operation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="annual_profit",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Годовая доходность, %"
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="description",
            field=models.CharField(
                blank=True, max_length=63, null=True, verbose_name="Описание программы"
            ),
        ),
    ]
