# Generated by Django 4.2.7 on 2024-06-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0074_program_annual_profit_program_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="annual_profit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Годовая доходность, %",
            ),
        ),
    ]
