# Generated by Django 4.2.7 on 2024-07-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0075_alter_program_annual_profit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogramaccrual",
            name="percent_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Доходность без учета комиссий",
            ),
        ),
    ]
