# Generated by Django 4.2.7 on 2024-07-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0076_userprogramaccrual_percent_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogramaccrual",
            name="percent_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Доходность без учета комиссий",
            ),
        ),
    ]
