# Generated by Django 4.2.7 on 2024-07-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0077_alter_userprogramaccrual_percent_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="created_at_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время создания заявки"
            ),
        ),
    ]
