# Generated by Django 4.2.7 on 2024-07-04 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0078_withdrawalrequest_created_at_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="created_at_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата и время создания заявки",
            ),
        ),
    ]
