# Generated by Django 4.2.7 on 2024-07-31 16:01

import core.localized.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0079_alter_withdrawalrequest_created_at_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="description",
            field=core.localized.fields.LocalizedTextField(
                blank=True,
                max_length=63,
                null=True,
                required=[],
                verbose_name="Описание программы",
            ),
        ),
    ]
