# Generated by Django 4.2.7 on 2024-09-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0080_alter_program_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="need_confirm",
            field=models.BooleanField(default=True),
        ),
    ]
