# Generated by Django 4.2.7 on 2024-01-31 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PreAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4)),
                (
                    "verify_type",
                    models.CharField(
                        choices=[("authorization", "Авторизация")], max_length=16
                    ),
                ),
                ("telegram_verify", models.BooleanField(default=False)),
                ("email_verify", models.BooleanField(default=False)),
                ("telegram_code", models.CharField(max_length=16)),
                ("email_code", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
