# Generated by Django 4.2.7 on 2024-02-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_telegram_id_preauthtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="agreement_applied",
        ),
        migrations.AddField(
            model_name="user",
            name="agreement_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время принятия лицензионного соглашения",
            ),
        ),
    ]
