# Generated by Django 4.2.7 on 2024-02-01 15:46

import apps.accounts.models.docs
import core.localized.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_telegram_id_preauthtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docs",
            name="file",
            field=core.localized.fields.LocalizedFileField(
                required=["ru"],
                upload_to=apps.accounts.models.docs.get_upload_path,
                verbose_name="Файл документа",
            ),
        ),
    ]
