# Generated by Django 4.2.7 on 2024-02-01 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_user_agreement_applied_user_agreement_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addressverification",
            options={
                "verbose_name": "Документ, подтверждающий адрес",
                "verbose_name_plural": "Документы, подтверждающие адрес",
            },
        ),
        migrations.AlterModelOptions(
            name="personalverification",
            options={
                "verbose_name": "Документ, подтверждающий личность",
                "verbose_name_plural": "Документы, подтверждающие личность",
            },
        ),
        migrations.AlterField(
            model_name="personalverification",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("passport", "Паспорт"),
                    ("id_card", "ID карта"),
                    ("driver_license", "Водительские права"),
                    ("residence_permit", "Вид на жительство"),
                ],
                verbose_name="Document type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.region",
                verbose_name="Регион",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram",
            field=models.CharField(
                blank=True, max_length=127, null=True, verbose_name="Телеграм"
            ),
        ),
    ]
