# Generated by Django 4.2.7 on 2024-02-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_addressverification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressverification",
            name="reject_message",
            field=models.TextField(blank=True, verbose_name="Причина отказа"),
        ),
        migrations.AddField(
            model_name="personalverification",
            name="reject_message",
            field=models.TextField(blank=True, verbose_name="Причина отказа"),
        ),
    ]
