# Generated by Django 4.2.7 on 2024-02-05 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_docs_file"),
        ("accounts", "0005_addressverification_reject_message_and_more"),
    ]

    operations = []
