# Generated by Django 4.2.7 on 2024-02-05 09:40

import apps.accounts.models.user
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_user_is_staff_settingsauthcodes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalverification",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.accounts.models.user.get_id_doc_upload_path,
                verbose_name="File",
            ),
        ),
    ]
