# Generated by Django 4.2.7 on 2024-02-05 09:42

import apps.accounts.models.user
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_personalverification_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressverification",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.accounts.models.user.get_addr_doc_upload_path,
                verbose_name="File",
            ),
        ),
    ]
