# Generated by Django 4.2.7 on 2024-02-06 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # ("accounts", "0007_alter_user_is_staff"),
        ("accounts", "0009_alter_addressverification_file"),
    ]

    operations = []
