# Generated by Django 4.2.7 on 2024-02-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_merge_20240206_1314"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingsauthcodes",
            name="destination",
            field=models.CharField(
                choices=[("email", "Email"), ("telegram", "Telegram")], default="email"
            ),
            preserve_default=False,
        ),
    ]
