# Generated by Django 4.2.7 on 2024-02-08 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_settingsauthcodes_destination"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partner_id",
                    models.IntegerField(
                        unique=True,
                        verbose_name="ID партнёра в системе GOODWIN, вводится вручную",
                    ),
                ),
                (
                    "partner_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.27,
                        max_digits=3,
                        verbose_name="Комиссия филиала/партнёра",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="accounts.region",
                        verbose_name="Регион",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь-партнёр",
                    ),
                ),
            ],
        ),
    ]
