# Generated by Django 4.2.7 on 2024-02-08 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_partner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={"verbose_name": "Партнёр", "verbose_name_plural": "Партнёры"},
        ),
        migrations.AlterField(
            model_name="partner",
            name="partner_id",
            field=models.IntegerField(
                unique=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="ID партнёра в системе GOODWIN, вводится вручную",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partners",
                to="accounts.region",
                verbose_name="Регион",
            ),
            preserve_default=False,
        ),
    ]
