# Generated by Django 4.2.7 on 2024-02-08 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_partner_partner_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="partner_fee",
            field=models.IntegerField(
                default=27,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxLengthValidator(100),
                ],
                verbose_name="Процент комиссии филиала/партнёра",
            ),
        ),
    ]
