# Generated by Django 4.2.7 on 2024-02-08 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_alter_partner_partner_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="partner_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.27,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Комиссия филиала/партнёра",
            ),
        ),
    ]
