# Generated by Django 4.2.7 on 2024-02-08 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_alter_partner_partner_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="partner_id",
            field=models.IntegerField(
                unique=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="ID партнёра в системе GOODWIN",
            ),
        ),
    ]
