# Generated by Django 4.2.7 on 2024-02-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_alter_partner_partner_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="inviter",
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.partner",
                verbose_name="Регион",
            ),
        ),
    ]
