# Generated by Django 4.2.7 on 2024-02-12 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_registerconfirmation"),
        ("accounts", "0017_alter_partner_partner_id"),
    ]

    operations = []
