# Generated by Django 4.2.7 on 2024-02-12 09:18

import apps.accounts.models.user
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_merge_20240212_1142"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.accounts.models.user.get_upload_path,
                verbose_name="Аватар",
            ),
        ),
    ]
