# Generated by Django 4.2.7 on 2024-02-09 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_remove_user_inviter_alter_user_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "Регион", "verbose_name_plural": "Регионы"},
        ),
    ]
