# Generated by Django 4.2.7 on 2024-02-09 09:49

import apps.accounts.models.user
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_alter_region_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressverification",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("registration", "Прописка"),
                    ("utility_bill", "Счёт за коммунальные услуги"),
                    ("bank_statement", "Банковская выписка"),
                    ("other", "Другое"),
                ],
                default="registration",
                verbose_name="Тип документа",
            ),
        ),
        migrations.AlterField(
            model_name="addressverification",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="addressverification",
            name="city",
            field=models.CharField(max_length=255, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="addressverification",
            name="country",
            field=models.CharField(max_length=255, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="addressverification",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.accounts.models.user.get_addr_doc_upload_path,
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="addressverification",
            name="postal_code",
            field=models.CharField(max_length=20, verbose_name="Почтовый индекс"),
        ),
        migrations.AlterField(
            model_name="addressverification",
            name="status",
            field=models.CharField(
                choices=[
                    ("no_data", "Нет данных"),
                    ("check", "Идёт проверка"),
                    ("approved", "Принято"),
                    ("rejected", "Отказано"),
                ],
                default="no_data",
                verbose_name="Статус проверки",
            ),
        ),
        migrations.AlterField(
            model_name="personalverification",
            name="date_of_birth",
            field=models.DateField(verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="personalverification",
            name="document_issue_date",
            field=models.DateField(verbose_name="Дата выдачи документа"),
        ),
        migrations.AlterField(
            model_name="personalverification",
            name="document_issue_region",
            field=models.CharField(
                max_length=255, verbose_name="Регион выдачи документа"
            ),
        ),
        migrations.AlterField(
            model_name="personalverification",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("passport", "Паспорт"),
                    ("id_card", "ID карта"),
                    ("driver_license", "Водительские права"),
                    ("residence_permit", "Вид на жительство"),
                ],
                verbose_name="Тип документа",
            ),
        ),
        migrations.AlterField(
            model_name="personalverification",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.accounts.models.user.get_id_doc_upload_path,
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="personalverification",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="personalverification",
            name="gender",
            field=models.CharField(
                choices=[("male", "Мужской"), ("female", "Женский")], verbose_name="Пол"
            ),
        ),
        migrations.AlterField(
            model_name="personalverification",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="personalverification",
            name="status",
            field=models.CharField(
                choices=[
                    ("no_data", "Нет данных"),
                    ("check", "Идёт проверка"),
                    ("approved", "Принято"),
                    ("rejected", "Отказано"),
                ],
                default="no_data",
                verbose_name="Статус проверки",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="email_request_code_on_auth",
            field=models.BooleanField(
                default=True, verbose_name="(email) Запрашивать код при входе в кабинет"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="email_request_code_on_withdrawal",
            field=models.BooleanField(
                default=True, verbose_name="(email) Запрашивать код при выводе средств"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="telegram_request_code_on_auth",
            field=models.BooleanField(
                default=True,
                verbose_name="(telegram) Запрашивать код при входе в кабинет",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="telegram_request_code_on_withdrawal",
            field=models.BooleanField(
                default=False,
                verbose_name="(telegram) Запрашивать код при выводе средств",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_is_confirmed",
            field=models.BooleanField(
                default=False, verbose_name="Электронная почта подтверждена"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.partner",
                verbose_name="Регион привязки",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Телеграмм ID"
            ),
        ),
    ]
