# Generated by Django 4.2.7 on 2024-02-09 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_addressverification_document_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="settings",
            options={"verbose_name": "Настройки", "verbose_name_plural": "Настройки"},
        ),
        migrations.AlterField(
            model_name="partner",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь-партнёр",
            ),
        ),
    ]
