# Generated by Django 4.2.7 on 2024-02-12 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_merge_20240212_1142"),
        ("accounts", "0021_alter_settings_options_alter_partner_user"),
    ]

    operations = []
