# Generated by Django 4.2.7 on 2024-02-12 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_user_avatar"),
        ("accounts", "0022_merge_20240212_1147"),
    ]

    operations = []
