# Generated by Django 4.2.7 on 2024-02-13 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_merge_0019_user_avatar_0022_merge_20240212_1147"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="region",
            new_name="partner",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_is_confirmed",
        ),
    ]
