# Generated by Django 4.2.7 on 2024-02-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_rename_region_user_partner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="email_request_code_on_transfer",
            field=models.BooleanField(
                default=True,
                verbose_name="(email) Запрашивать код при внутреннем переводе",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="telegram_request_code_on_transfer",
            field=models.BooleanField(
                default=True,
                verbose_name="(telegram) Запрашивать код при внутреннем переводе",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="telegram_request_code_on_auth",
            field=models.BooleanField(
                default=False,
                verbose_name="(telegram) Запрашивать код при входе в кабинет",
            ),
        ),
    ]
