# Generated by Django 4.2.7 on 2024-02-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_settings_email_request_code_on_transfer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="telegram_request_code_on_transfer",
            field=models.BooleanField(
                default=False,
                verbose_name="(telegram) Запрашивать код при внутреннем переводе",
            ),
        ),
    ]
