# Generated by Django 4.2.7 on 2024-02-27 14:09

import core.localized.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_alter_settings_telegram_request_code_on_transfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docs",
            name="file",
            field=core.localized.fields.LocalizedFileField(
                required=["ru"], upload_to="documents", verbose_name="Файл документа"
            ),
        ),
    ]
