# Generated by Django 4.2.7 on 2024-02-29 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_alter_docs_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registerconfirmation",
            name="region",
        ),
        migrations.AddField(
            model_name="registerconfirmation",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.partner",
                verbose_name="Регион привязки",
            ),
        ),
    ]
