# Generated by Django 4.2.7 on 2024-02-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0028_remove_registerconfirmation_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.partner",
                verbose_name="Привязан к партнёру",
            ),
        ),
    ]
