# Generated by Django 4.2.7 on 2024-04-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0031_emailchangeconfirmation"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCountHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        verbose_name="Кол-во зарегистрированных пользователей"
                    ),
                ),
                (
                    "active",
                    models.PositiveIntegerField(
                        verbose_name="Кол-во активных пользователей"
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, unique=True)),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "История пользователей",
            },
        ),
    ]
