# Generated by Django 4.2.7 on 2024-04-25 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0032_usercounthistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={"verbose_name": "Филиал", "verbose_name_plural": "Филиалы"},
        ),
    ]
