# Generated by Django 4.2.7 on 2024-05-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_alter_partner_partner_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=63, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Доступна для выбора"
                    ),
                ),
            ],
            options={
                "verbose_name": "страну",
                "verbose_name_plural": "Страны (для верификации)",
            },
        ),
    ]
