# Generated by Django 4.2.7 on 2024-05-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["name"],
                "verbose_name": "страну",
                "verbose_name_plural": "Страны (для верификации)",
            },
        ),
    ]
