# Generated by Django 4.2.7 on 2024-05-23 13:46

import core.localized.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_alter_country_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("incorrect_value", "Неверное значение"),
                            ("fill_required", "Обязательно к заполнению"),
                            ("insufficient_funds", "Недостаточно средств"),
                            ("invalid_email", "Неверный Email"),
                            ("invalid_password", "Неверный пароль"),
                            ("user_not_found", "Пользователь не найден"),
                            ("password_mismatch", "Пароли не совпадают"),
                            ("strong_password", "Надёжный пароль"),
                            ("same_email", "Email существует"),
                            ("invalid_code", "Неверный код"),
                            ("fill_in_field", "Заполните поле"),
                            ("email_at_sign", "Email должен содержать @"),
                            ("email_at_after", "Адрес email неполный"),
                            ("weak_password", "Слабый пароль"),
                        ]
                    ),
                ),
                (
                    "text",
                    core.localized.fields.LocalizedTextField(
                        required=["ru"], verbose_name="Основной текст"
                    ),
                ),
            ],
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "Уведомления в истории операций",
            },
        ),
    ]
