# Generated by Django 4.2.7 on 2024-05-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_errormessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="errormessage",
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "Уведомления об ошибках",
            },
        ),
    ]
