# Generated by Django 4.2.7 on 2024-05-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_alter_errormessage_error_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errormessage",
            name="error_type",
            field=models.CharField(
                choices=[
                    ("incorrect_value", "Неверное значение"),
                    ("fill_required", "Обязательно к заполнению"),
                    ("insufficient_funds", "Недостаточно средств"),
                    ("user_email_mismatch", "Email не совпадает"),
                    ("invalid_email", "Неверный Email"),
                    ("invalid_password", "Неверный пароль"),
                    ("user_not_found", "Пользователь не найден"),
                    ("password_mismatch", "Пароли не совпадают"),
                    ("strong_password", "Надёжный пароль"),
                    ("same_email", "Email существует"),
                    ("invalid_code", "Неверный код"),
                    ("fill_in_field", "Заполните поле"),
                    ("email_at_sign", "Email должен содержать @"),
                    ("email_at_after", "Адрес email неполный"),
                    ("weak_password", "Слабый пароль"),
                    ("min_program_deposit", "Минимальный депозит программы"),
                    (
                        "min_program_replenishment",
                        "Минимальная сумма пополнения программы",
                    ),
                    (
                        "min_cancel_replenishment",
                        "Минимальный остаток пополнения программы",
                    ),
                    (
                        "min_cancel_program_deposit",
                        "Минимальный остаток депозита программы",
                    ),
                    ("insufficient_deposit", "Сумма закрытия больше депозита"),
                    (
                        "insufficient_cancel_amount",
                        "Сумма отмены больше суммы пополнения",
                    ),
                    ("self_transfer", "Перевод самому себе"),
                ]
            ),
        ),
    ]
