# Generated by Django 4.2.7 on 2024-05-24 09:53

import core.localized.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_alter_errormessage_error_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("auth_confirm", "Подтверждение почты"),
                            ("password_recovery", "Восстановление пароля"),
                            ("password_change", "Изменение пароля"),
                            ("settings_change", "Изменение настроек профиля"),
                            ("email_change", "Изменение почты"),
                        ]
                    ),
                ),
                (
                    "title",
                    core.localized.fields.LocalizedTextField(
                        required=["ru"], verbose_name="Заголовок"
                    ),
                ),
                (
                    "text",
                    core.localized.fields.LocalizedTextField(
                        required=["ru"], verbose_name="Основной текст"
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "Шаблоны email-сообщений",
            },
        ),
    ]
