# Generated by Django 4.2.7 on 2024-05-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_emailmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("auth_confirm", "Подтверждение почты"),
                    ("password_recovery", "Восстановление пароля"),
                    ("password_change", "Изменение пароля"),
                    ("settings_change", "Изменение настроек профиля"),
                    ("email_change", "Изменение почты"),
                    ("operation_confirm", "Подтверждение операции"),
                ]
            ),
        ),
    ]
