# Generated by Django 4.2.7 on 2024-05-31 11:12

import apps.accounts.models.user
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_alter_emailmessage_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="partner_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("27.0"),
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Комиссия филиала/партнёра",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="partner_id",
            field=models.IntegerField(
                default=apps.accounts.models.user.get_partner_id,
                unique=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="ID филиала",
            ),
        ),
    ]
