# Generated by Django 4.2.7 on 2024-05-31 11:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_alter_partner_partner_fee_alter_partner_partner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="partner_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("27.0"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Комиссия филиала/партнёра",
            ),
        ),
    ]
