# Generated by Django 4.2.7 on 2024-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_alter_partner_partner_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="business_account",
            field=models.BooleanField(default=False),
        ),
    ]
