# Generated by Django 4.2.7 on 2024-06-11 09:01

import apps.accounts.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_user_business_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessAccount",
            fields=[],
            options={
                "verbose_name": "Бизнес-аккаунт",
                "verbose_name_plural": "Бизнес-аккаунт",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
            managers=[
                ("objects", apps.accounts.models.user.UserManager()),
            ],
        ),
    ]
