# Generated by Django 4.2.7 on 2024-02-06 10:25

import core.localized.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateTelegramMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("greetings", "Приветствие"),
                            ("notify_connected", "Уведомления подключены"),
                            ("notify_disconnected", "Уведомления отключены"),
                            ("PROGRAM_START", "Запуск программы"),
                            ("PROGRAM_STARTED", "Программа запущена"),
                            ("PROGRAM_CLOSING", "Закрытие программы"),
                            ("frozen_available", "Доступны замороженные активы"),
                            ("start_with_replenishment", "Запуск с учетом пополнения"),
                            (
                                "CANCELING_PROGRAM_REPLENISHMENT",
                                "Отмена пополнения программы",
                            ),
                            ("premature_defrost", "Досрочная разморозка"),
                            ("withdrawal_request", "Заявка на вывод"),
                            ("successful_transfer", "Успешный перевод"),
                            ("transfer_rejected", "Перевод отклонен"),
                            (
                                "internal_transfer_for_sender",
                                "Внутренний перевод (для отправителя)",
                            ),
                            (
                                "internal_transfer_for_recipient",
                                "Внутренний перевод (для получателя)",
                            ),
                            ("program_profit", "Прибыль по программе"),
                        ],
                        max_length=32,
                        unique=True,
                        verbose_name="Тип сообщения",
                    ),
                ),
                (
                    "text",
                    core.localized.fields.LocalizedTextField(
                        required=["ru"], verbose_name="Основной текст"
                    ),
                ),
            ],
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "Уведомления в телеграм",
            },
        ),
    ]
