# Generated by Django 4.2.7 on 2024-05-03 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0002_templatetelegrammessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminTelegramAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=127, verbose_name="Тег")),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, verbose_name="Токен привязки"),
                ),
                (
                    "telegram_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Телеграм ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "аккаунт",
                "verbose_name_plural": "Telegram-аккаунты для уведомлений",
            },
        ),
    ]
