# Generated by Django 4.2.7 on 2024-05-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0003_admintelegramaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatetelegrammessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("greetings", "Приветствие"),
                    ("notify_connected", "Уведомления подключены"),
                    ("notify_disconnected", "Уведомления отключены"),
                    ("PROGRAM_START", "Запуск программы"),
                    ("PROGRAM_STARTED", "Программа запущена"),
                    ("PROGRAM_CLOSING", "Закрытие программы"),
                    ("frozen_available", "Доступны замороженные активы"),
                    ("start_with_replenishment", "Запуск с учетом пополнения"),
                    ("CANCELING_PROGRAM_REPLENISHMENT", "Отмена пополнения программы"),
                    ("premature_defrost", "Досрочная разморозка"),
                    ("withdrawal_request", "Заявка на вывод"),
                    ("successful_transfer", "Успешный перевод"),
                    ("transfer_rejected", "Перевод отклонен"),
                    (
                        "internal_transfer_for_sender",
                        "Внутренний перевод (для отправителя)",
                    ),
                    (
                        "internal_transfer_for_recipient",
                        "Внутренний перевод (для получателя)",
                    ),
                    ("program_profit", "Прибыль по программе"),
                    ("program_loss", "Убыток по программе"),
                ],
                max_length=32,
                unique=True,
                verbose_name="Тип сообщения",
            ),
        ),
    ]
