# Generated by Django 4.2.7 on 2024-04-15 09:27

import core.localized.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Support",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("wechat", "Wechat"),
                            ("whatsapp", "Whatsapp"),
                        ],
                        verbose_name="Сервис",
                    ),
                ),
                (
                    "link",
                    core.localized.fields.LocalizedURLField(
                        blank=True, required=[], verbose_name="Ссылка"
                    ),
                ),
            ],
        ),
    ]
