# Generated by Django 4.2.7 on 2024-04-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="support",
            name="service",
            field=models.CharField(max_length=15, verbose_name="Сервис"),
        ),
    ]
