# Generated by Django 4.2.7 on 2024-04-15 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0002_alter_support_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="support",
            options={
                "ordering": ["service"],
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
