# Generated by Django 4.2.7 on 2024-04-15 09:32

import core.localized.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0003_alter_support_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="support",
            name="link",
            field=core.localized.fields.LocalizedCharField(
                blank=True, required=[], verbose_name="Ссылка"
            ),
        ),
    ]
