# Generated by Django 4.2.7 on 2024-04-15 10:56

import apps.support.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0004_alter_support_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="support",
            name="logo",
            field=models.ImageField(
                null=True, upload_to=apps.support.models.get_upload_path
            ),
        ),
    ]
