# Generated by Django 4.2.7 on 2024-04-15 11:01

import apps.support.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0005_support_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="support",
            name="logo",
            field=models.FileField(
                null=True, upload_to=apps.support.models.get_upload_path
            ),
        ),
    ]
