# Generated by Django 4.2.7 on 2024-02-05 11:38

import core.localized.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    core.localized.fields.LocalizedCharField(
                        max_length=255, required=["ru"]
                    ),
                ),
                ("text", core.localized.fields.LocalizedTextField(required=["ru"])),
                (
                    "image",
                    core.localized.fields.LocalizedFileField(
                        blank=True, null=True, required=[], upload_to="faq/answer/"
                    ),
                ),
                (
                    "video",
                    core.localized.fields.LocalizedURLField(blank=True, required=[]),
                ),
            ],
            options={
                "verbose_name": "Вопрос-ответ",
                "verbose_name_plural": "Вопрос-ответ",
            },
        ),
    ]
