# Generated by Django 4.2.7 on 2024-01-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="faq/answer/"),
                ),
                ("video", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Вопрос-ответ",
                "verbose_name_plural": "Вопрос-ответ",
            },
        ),
    ]
