# Generated by Django 4.2.7 on 2024-01-31 15:54

import core.localized.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="image",
            field=core.localized.fields.LocalizedFileField(
                blank=True, null=True, required=[], upload_to="faq/answer/"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=core.localized.fields.LocalizedTextField(required=["ru"]),
        ),
        migrations.AlterField(
            model_name="answer",
            name="title",
            field=core.localized.fields.LocalizedCharField(
                max_length=255, required=["ru"]
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="video",
            field=core.localized.fields.LocalizedURLField(blank=True, required=[]),
        ),
    ]
