# Generated by Django 4.2.7 on 2024-06-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0074_program_annual_profit_program_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProgram",
            fields=[],
            options={
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы на GDW-сайте",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.program",),
        ),
        migrations.CreateModel(
            name="FundProfitStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("percent", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gdw_site.siteprogram",
                    ),
                ),
            ],
        ),
    ]
