# Generated by Django 4.2.7 on 2024-06-25 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundTotalStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2021),
                            django.core.validators.MaxValueValidator(2024),
                        ],
                        verbose_name="Год",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "Январь"),
                            (3, "Март"),
                            (5, "Май"),
                            (7, "Июль"),
                            (9, "Сентябрь"),
                            (11, "Ноябрь"),
                        ],
                        verbose_name="Месяц",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Суммарный доход (%)",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="fundprofitstats",
            unique_together={("program", "date")},
        ),
    ]
