# Generated by Django 4.2.7 on 2024-06-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0002_fundtotalstats_alter_fundprofitstats_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fundtotalstats",
            unique_together={("year", "month")},
        ),
    ]
