# Generated by Django 4.2.7 on 2024-06-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0003_alter_fundtotalstats_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fundtotalstats",
            options={"ordering": ["year", "month"]},
        ),
    ]
