# Generated by Django 4.2.7 on 2024-06-25 12:07

import core.localized.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0004_alter_fundtotalstats_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    core.localized.fields.LocalizedCharField(
                        max_length=255, required=["ru"]
                    ),
                ),
                ("text", core.localized.fields.LocalizedTextField(required=["ru"])),
            ],
            options={
                "verbose_name": "Вопрос-ответ для сайта",
                "verbose_name_plural": "Вопрос-ответ для сайта",
            },
        ),
    ]
