# Generated by Django 4.2.7 on 2024-06-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0005_siteanswer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fundtotalstats",
            options={
                "ordering": ["year", "month"],
                "verbose_name": "значение",
                "verbose_name_plural": "Статистика фонда",
            },
        ),
    ]
