# Generated by Django 4.2.7 on 2024-06-25 12:39

from django.db import migrations, models
import django_admin_geomap


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0006_alter_fundtotalstats_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "certificate",
                    models.CharField(max_length=255, verbose_name="Сертификат"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("latitude", models.FloatField(verbose_name="Широта")),
                ("longitude", models.FloatField(verbose_name="Долгота")),
            ],
            options={
                "verbose_name": "значения",
                "verbose_name_plural": "Контакты",
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
