# Generated by Django 4.2.7 on 2024-06-25 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0007_sitecontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundtotalstats",
            name="year",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(2021)],
                verbose_name="Год",
            ),
        ),
    ]
