# Generated by Django 4.2.7 on 2024-06-25 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0008_alter_fundtotalstats_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundDailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("percent", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                "verbose_name": "значение",
                "verbose_name_plural": "Ежедневная статистика (для калькулятора)",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="FundMonthlyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2021)],
                        verbose_name="Год",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "Январь"),
                            (2, "Февраль"),
                            (3, "Март"),
                            (4, "Апрель"),
                            (5, "Май"),
                            (6, "Июнь"),
                            (7, "Июль"),
                            (8, "Август"),
                            (9, "Сентябрь"),
                            (10, "Октябрь"),
                            (11, "Ноябрь"),
                            (12, "Декабрь"),
                        ],
                        verbose_name="Месяц",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Суммарный доход (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "значение",
                "verbose_name_plural": "Статистика фонда (для графика)",
                "ordering": ["year", "month"],
                "unique_together": {("year", "month")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="fundprofitstats",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="fundprofitstats",
            name="program",
        ),
        migrations.DeleteModel(
            name="FundTotalStats",
        ),
        migrations.DeleteModel(
            name="FundProfitStats",
        ),
    ]
