# Generated by Django 4.2.7 on 2024-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0009_funddailystats_fundmonthlystats_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funddailystats",
            options={
                "ordering": ["date"],
                "verbose_name": "значение",
                "verbose_name_plural": "Статистика по дням (для калькулятора)",
            },
        ),
        migrations.AlterModelOptions(
            name="fundmonthlystats",
            options={
                "ordering": ["year", "month"],
                "verbose_name": "значение",
                "verbose_name_plural": "Статистика по месяцам (для графика)",
            },
        ),
        migrations.AlterField(
            model_name="funddailystats",
            name="date",
            field=models.DateField(unique=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="funddailystats",
            name="percent",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Прибыль (%)"
            ),
        ),
    ]
