# Generated by Django 4.2.7 on 2024-06-26 11:11

import apps.gdw_site.models.news
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0010_alter_funddailystats_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.PositiveIntegerField(unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.gdw_site.models.news.get_upload_path,
                        verbose_name="Изображение",
                    ),
                ),
                ("text", models.TextField()),
            ],
            options={
                "ordering": ["-message_id"],
            },
        ),
    ]
