# Generated by Django 4.2.7 on 2024-06-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0011_sitenews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitenews",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
