# Generated by Django 4.2.7 on 2024-06-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0012_alter_sitenews_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitenews",
            name="is_relevant",
            field=models.BooleanField(default=True),
        ),
    ]
