# Generated by Django 4.2.7 on 2024-06-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0013_sitenews_is_relevant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitenews",
            options={
                "ordering": ["-message_id"],
                "verbose_name": "новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.AlterField(
            model_name="sitenews",
            name="message_id",
            field=models.PositiveIntegerField(unique=True, verbose_name="ID"),
        ),
    ]
