# Generated by Django 4.2.7 on 2024-06-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0014_alter_sitenews_options_alter_sitenews_message_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=63)),
            ],
            options={
                "verbose_name_plural": "Новостные теги",
            },
        ),
        migrations.AddField(
            model_name="sitenews",
            name="title",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="sitenews",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
        migrations.AddField(
            model_name="sitenews",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news",
                to="gdw_site.newstags",
                verbose_name="Тег",
            ),
        ),
    ]
