# Generated by Django 4.2.7 on 2024-06-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0015_newstags_sitenews_title_alter_sitenews_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newstags",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitenews",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="newstags",
            name="tag",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
