# Generated by Django 4.2.7 on 2024-06-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0016_newstags_is_active_sitenews_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newstags",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="sitenews",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="sitenews",
            name="is_relevant",
        ),
        migrations.AddField(
            model_name="sitenews",
            name="is_sync",
            field=models.BooleanField(default=True, verbose_name="Синхронизирован"),
        ),
        migrations.AddField(
            model_name="sitenews",
            name="show_on_site",
            field=models.BooleanField(default=True, verbose_name="Показывать на сайте"),
        ),
        migrations.AddField(
            model_name="sitenews",
            name="sync_with_tg",
            field=models.BooleanField(
                default=False, verbose_name="Синхронизация с Telegram-каналом"
            ),
        ),
        migrations.AlterField(
            model_name="sitenews",
            name="message_id",
            field=models.PositiveIntegerField(
                null=True, unique=True, verbose_name="ID поста"
            ),
        ),
    ]
