# Generated by Django 4.2.7 on 2024-06-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gdw_site",
            "0017_remove_newstags_is_active_remove_sitenews_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitenews",
            name="message_id",
            field=models.PositiveIntegerField(
                null=True, unique=True, verbose_name="ID поста в Telegram"
            ),
        ),
        migrations.AlterField(
            model_name="sitenews",
            name="sync_with_tg",
            field=models.BooleanField(
                default=False, verbose_name="Синхронизировать с Telegram"
            ),
        ),
    ]
