# Generated by Django 4.2.7 on 2024-06-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0018_alter_sitenews_message_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitenews",
            name="edited_by_admin",
            field=models.BooleanField(default=False),
        ),
    ]
