# Generated by Django 4.2.7 on 2024-07-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0019_sitenews_edited_by_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitenews",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата публикации"
            ),
        ),
    ]
