# Generated by Django 4.2.7 on 2024-07-08 13:28

import core.localized.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0020_sitenews_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=15, verbose_name="Сервис")),
                (
                    "link",
                    core.localized.fields.LocalizedCharField(
                        blank=True, required=[], verbose_name="Ссылка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["service"],
            },
        ),
    ]
