# Generated by Django 4.2.7 on 2024-07-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0021_socialcontact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialcontact",
            options={
                "ordering": ["service"],
                "verbose_name": "соцсеть",
                "verbose_name_plural": "Соцсети",
            },
        ),
    ]
