# Generated by Django 4.2.7 on 2024-07-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0022_alter_socialcontact_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                ("url", models.URLField()),
            ],
        ),
    ]
