# Generated by Django 4.2.7 on 2024-07-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0023_maindomain"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedirectLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[("register", "Регистрация"), ("login", "Логин")],
                        verbose_name="Действие",
                    ),
                ),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "ссылка",
                "verbose_name_plural": "Ссылки для аутентификации",
            },
        ),
        migrations.DeleteModel(
            name="MainDomain",
        ),
    ]
