# Generated by Django 4.2.7 on 2024-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0024_redirectlinks_delete_maindomain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirectlinks",
            name="link_type",
            field=models.CharField(
                choices=[("register", "Регистрация"), ("login", "Логин")],
                unique=True,
                verbose_name="Действие",
            ),
        ),
    ]
