# Generated by Django 4.2.7 on 2024-07-08 14:19

import core.localized.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0025_alter_redirectlinks_link_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialcontact",
            name="service",
            field=core.localized.fields.LocalizedCharField(
                max_length=15, required=["ru"], verbose_name="Сервис"
            ),
        ),
    ]
