# Generated by Django 4.2.7 on 2024-07-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0027_alter_socialcontact_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funddailystats",
            options={
                "ordering": ["date"],
                "verbose_name": "значение",
                "verbose_name_plural": "Ежедневная доходность фонда",
            },
        ),
    ]
