# Generated by Django 4.2.7 on 2024-07-09 09:27

import apps.gdw_site.models.social
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0028_alter_funddailystats_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialcontact",
            name="logo",
            field=models.FileField(
                null=True, upload_to=apps.gdw_site.models.social.get_upload_path
            ),
        ),
    ]
