# Generated by Django 4.2.7 on 2024-07-09 14:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0029_socialcontact_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funddailystats",
            name="percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                max_digits=6,
                verbose_name="Прибыль (%)",
            ),
        ),
    ]
