# Generated by Django 4.2.7 on 2024-07-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0030_alter_funddailystats_percent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newstags",
            options={
                "ordering": ["tag"],
                "verbose_name": "тег",
                "verbose_name_plural": "Новостные теги",
            },
        ),
    ]
