# Generated by Django 4.2.7 on 2024-07-15 08:32

import apps.gdw_site.models.news
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0031_alter_newstags_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsTagsEng",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=63, unique=True)),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "Новостные теги",
                "ordering": ["tag"],
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="NewsTags",
            new_name="NewsTagsRus",
        ),
        migrations.RenameModel(
            old_name="SiteNews",
            new_name="SiteNewsRus",
        ),
        migrations.AlterModelOptions(
            name="sitenewsrus",
            options={
                "ordering": ["-date"],
                "verbose_name": "новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.CreateModel(
            name="SiteNewsEng",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.PositiveIntegerField(
                        null=True, unique=True, verbose_name="ID поста в Telegram"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.gdw_site.models.news.get_upload_path,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Заголовок"
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="Текст")),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "is_sync",
                    models.BooleanField(default=True, verbose_name="Синхронизирован"),
                ),
                (
                    "show_on_site",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "sync_with_tg",
                    models.BooleanField(
                        default=False, verbose_name="Синхронизировать с Telegram"
                    ),
                ),
                ("edited_by_admin", models.BooleanField(default=False)),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news",
                        to="gdw_site.newstagseng",
                        verbose_name="Тег",
                    ),
                ),
            ],
            options={
                "verbose_name": "новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
    ]
