# Generated by Django 4.2.7 on 2024-07-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gdw_site", "0032_newstagseng_rename_newstags_newstagsrus_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newstagseng",
            options={"verbose_name_plural": "Новостные теги (EN)"},
        ),
        migrations.AlterModelOptions(
            name="newstagsrus",
            options={"verbose_name_plural": "Новостные теги (RU)"},
        ),
        migrations.AlterModelOptions(
            name="sitenewseng",
            options={"verbose_name_plural": "Новости (EN)"},
        ),
        migrations.AlterModelOptions(
            name="sitenewsrus",
            options={"verbose_name_plural": "Новости (RU)"},
        ),
    ]
