# Generated by Django 4.2.7 on 2024-08-01 08:49

import core.localized.fields
from django.db import migrations, models


def forwards1(apps, _):
    RedirectLinks = apps.get_model("gdw_site", "RedirectLinks")
    RedirectLinks.objects.update(url=None)


def forwards2(apps, _):
    RedirectLinks = apps.get_model("gdw_site", "RedirectLinks")
    RedirectLinks.objects.update(url={"ru": "url"})


def backwards(apps, _):
    pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "gdw_site",
            "0033_alter_newstagseng_options_alter_newstagsrus_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirectlinks",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.RunPython(forwards1, backwards),
        migrations.AlterField(
            model_name="redirectlinks",
            name="url",
            field=core.localized.fields.LocalizedURLField(null=True, required=["ru"]),
        ),
        migrations.RunPython(forwards2, backwards),
        migrations.AlterField(
            model_name="redirectlinks",
            name="url",
            field=core.localized.fields.LocalizedURLField(required=["ru"]),
        ),
    ]
