# Generated by Django 4.2.7 on 2024-08-01 08:49

import core.localized.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "gdw_site",
            "0033_alter_newstagseng_options_alter_newstagsrus_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirectlinks",
            name="url",
            field=core.localized.fields.LocalizedURLField(required=["ru"]),
        ),
    ]
