name: Backend CI/CD

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Create env file'
        run: |
          echo "${{ secrets.MAIN_ENV_FILE }}" > .env

      - name: Build and run
        run: |
          docker-compose down
          docker image prune -f
          docker-compose up --build -d

  database:
    runs-on: [ self-hosted ]
    needs: deploy
    steps:
      - name: Migrations
        run: docker exec -t goodwin_backend python3 manage.py migrate --no-input
      
      - name: Activate program accruals
        run: docker exec -t goodwin_backend python3 manage.py activate_program_accruals
